- builder/imports/llvm.py
> Use curl instead of wget to get LLVM key

- builder/data.py
> Disable fuzz tests on clang 3, removed export of compile commands

- builder/__main__.py
- builder/actions/mirror.py
- builder/env.py
- builder/fetch.py
- builder/imports/jdk.py
- builder/project.py
The goal here is to reduce our reliance on public infrastructure where we can, and to reduce downloads where possible. We should be able to bake the cache into our docker images, or mount it as a tarball volume, for instance.
This is in preparation for the NDK, which is a couple gigs that I don't want to have to download everywhere all the time.
> Implemented publish to S3, mirror for JDK

- .github/docker-images/al2012-x64/Dockerfile
Offline compiled libcrypto 1.1.1 on al2012 and added to S3 binaries bucket.
> al2012 needs its own libcrypto because its linker is from the Phoenicians

- .github/workflows/sanity-test.yml
- builder/__main__.py
- builder/actions/release.py
- builder/shell.py
Sample output:
```
> python3 -m builder release-notes --project=../aws-crt-java            
Probing /etc/system-release
Amazon Linux release 2 (Karoo)
Host Environment:
Host: al2 x64
Target: linux x64
Compiler: default (version: 7) /usr/bin/gcc
Available Compilers: gcc 7, clang 7
Available Projects: 
Found branches: ['release-notes', 'remotes/origin/release-notes']
Working in branch: release-notes
Found project: aws-crt-java at /local/home/boswej/dev/aws-crt-java
> cd /local/home/boswej/dev/aws-crt-java
Source directory: /local/home/boswej/dev/aws-crt-java
Build directory: /local/home/boswej/dev/aws-crt-java/target/cmake-build
> rm -rf …
```
> Imported release notes script as an action

- .github/workflows/sanity-test.yml
- builder/__main__.py
Just forcing a rebuild of these docker images will pull the new manylinux bases.
Also fixed swift tests
> Rebuilding manylinux docker images with python 3.9

- builder/imports/nodejs.py
Changes to dependencies resulted in node not getting installed properly and when it did get installed it was using the minimum platform (10.0.0) rather than what we need (10.16+)
> Update how node is installed on windows CI builds so that it uses 10.16

- .github/workflows/create-release.yml
> Use release_tag output to get IMAGE_TAG to docker builds

- .github/docker-images/swift-5-ubuntu-16-x64/Dockerfile
- .github/docker-images/ubuntu-16-x64/Dockerfile
- .github/workflows/docker-images.yml
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Removed deprecated set-env calls

- builder/core/env.py
- builder/core/project.py
- builder/main.py
*Issue:*
wanted to pass `cmake_args=-DBUILD_SHARED_LIBS=ON` to builder and it didn't work right
- move all logic for fixing up cli_config to one place
- consult default KEYS to see if it should be a list
- fix bugs when reading in list args
- assume user wants to "!" override a list. Allow "+" for appending to defaults.
> Improved handling of cli config args.

- README.md
- builder/actions/cmake.py
- builder/core/data.py
- builder/core/env.py
- builder/imports/awslc.py
- builder/main.py
The existing `cmake_args` in the config does not affect the building of upstream dependencies
So add new CLI argument we can use like `--cmake-extra=-DBUILD_SHARED_LIBS=ON` and build everything in the tree with a given flag
> --cmake-extra lets you add extra cmake args to every project

- builder/actions/cmake.py
*Issue:*
GCC builds were freezing when building aws-lc.
We suspected it was due to too much parallelism.
Passing -j to make will do an unlimited amount of parallelism, so stop doing that.
Instead of passing -j through to make which causes unbounded parallelism, use CMAKE_BUILD_PARALLEL_LEVEL=cpu-count
> Use cpu-count for parallel builds

- builder/actions/cmake.py
- builder/core/env.py
- builder/core/shell.py
windows needs `install/bin` added to $PATH so tests can find DLLs
linux needs `install/lib` added to $LD_LIBRARY_PATH so tests can find .so
this cropped up on running aws-c-http's integration tests. which included launching ANOTHER python process that, in turn, launched a another executable
> fix linux-shared-lib tests

- .github/docker-images/ubuntu-16-x64/Dockerfile
Temporary workaround for old clang fetch failures by switching from ubuntu 16 to 18 as the base image.  Yes the container is still called ubuntu-16-x64 despite this change because updating every single ci.yml sounds like misery for a temp change (until we get  docker images with clang included available)
> Clang CI Temp Fix (hopefully)

- builder/actions/cmake.py
- builder/core/project.py
- set CMAKE_BUILD_PARALLEL_LEVEL before configuring, to speed up any builds during configure stage (I'm looking at you aws-lc.cmake)
- tweak tree traversal. it wasn't wrong before, but claimed to be a breadth search while it was actually a weird mix of both breadth and depth. now it's post-order traversal, which gets nice results
> trivial improvements

- .github/docker-images/swift-5-al2-x64/Dockerfile
- .github/docker-images/swift-5-centos-x64/Dockerfile
- .github/docker-images/swift-5-ubuntu-16-x64/Dockerfile
*Description of changes:* SSL Packages missing on swift images needed for proper ci checks in aws-crt-swift.
> add ssl packages to swift images for ci checks

- .github/docker-images/phpbrew-linux-x64/Dockerfile
- .github/workflows/docker-images.yml
> Force the PHP version to be supplied during docker builds

- .github/workflows/linux-container-ci.sh
Matches the pattern used by aws-c-s3 and all the CRTs
> Pass CI credentials to builder

- .github/docker-images/opensuse-leap/Dockerfile
- .github/docker-images/rhel8-x64/Dockerfile
**Issue:**
2 of the newer docker images didn't have the `sudo` command, which causes errors if a `builder.json` file tried to install something.
Add sudo to docker images that didn't already have it
> Add sudo to new docker images

- .github/docker-images/swift-5-ubuntu-x64/Dockerfile
*Description of changes:* Need java 11 on swift ubuntu image in order to run gradle build in sdk ci
> fix: add java 11 to ubuntu swift image

- .github/docker-images/swift-5-al2-x64/Dockerfile
- .github/docker-images/swift-5-centos-x64/Dockerfile
- .github/docker-images/swift-5-ubuntu-x64/Dockerfile
*Description of changes:* Directly following the release of Swift 5.5.3, this updates the docker images to use the new version which fixes a compiler bug when using Swift on Linux with async support.
> fix: add new docker images

- builder/actions/git.py
- builder/core/project.py
- tests/test_project.py
When processing aws-c-io, Builder wouldn't notice the fact that aws-c-cal was using a pinned version of aws-lc.
There were 2 reasons for this:
1) Builder was only doing fancy resolution of platform-specific dependencies for the main project. aws-c-cal only depends on aws-lc for nix platforms, but this wasn't being noticed. Now Builder does fancy resolution for all projects.
2) Builder was pulling dependencies in a weird order. Now builder tries to pull upstream stuff first, and downstream stuff last.
> Fix project dependency bug.

- builder/core/data.py
also remove macos-x86 flags. macos doesn't support 32bit anymore
> support macos-arm64 as target

- .github/docker-images/opensuse-leap/Dockerfile
- .github/docker-images/rhel8-x64/Dockerfile
- .github/docker-images/ubuntu-18-x64/Dockerfile
- builder/core/data.py
**Issue:**
aws-crt-python is removing support for python3.6: https://github.com/awslabs/aws-crt-python/pull/402
but several of our docker images are still using python3.6
**Description of change:**
For distros where python3.6 was the default (ubuntu18, rhel8), switch to using the newest python version available to that distro.
> Stop using python 3.6, which is long past end of life.

- .github/docker-images/ubuntu-20-x64/Dockerfile
- .github/workflows/create-channel.yml
- .github/workflows/create-release.yml
Python 3.6 is no longer supported and was the default for Ubuntu 16.
Added Ubuntu 20 whose default is Python 3.8.
> added ubuntu 20 x64

- .github/actions/check-submodules/package-lock.json
- .github/actions/check-submodules/package.json
- .github/actions/release-tag/package-lock.json
- .github/actions/release-tag/package.json
This is a copy of a dependebot PR: https://github.com/awslabs/aws-crt-builder/pull/207
> Bump @vercel/ncc from 0.34.0 to 0.36.0

- README.md
- builder/actions/cmake.py
- builder/core/shell.py
- builder/main.py
- Add `--gcc-coverage`, to generate code coverage repo if available. 
- Only works for using Cmake and GCC as compiler. 
- We could involve more time to make a more generic solution for different compiler, but for real, we only need one working case for the report to work. So, it's not really worth to put time on it for now. We can come back later if we need more case.
> add --coverage

- builder/actions/cmake.py
- builder/core/shell.py
- builder/core/toolchain.py
- builder/core/util.py
**Issue:**
The output of a failing command prints twice, making the logs hard to parse.
**Diagnosis:**
It prints once when the command runs, then the output is added to an exception which gets printed out again.
I don't know why the output was ever added to the exception. This was changed 1.5 years ago, but there's no real explanation why in the PR: https://github.com/awslabs/aws-crt-builder/pull/129
This also risks leaking secrets when the command is run with `quiet=True`
- Remove output from Exception
- Use named keyword arguments instead of `**kwargs` so it's easier to figure out what all the options are
- Helpers for stringifying commands args
> don't repeat output of failed command

- builder/actions/install.py
- builder/core/data.py
- builder/core/host.py
N/A
Adds OpenBSD as a supported host. Tested by running builds of aws-lc, s2n-tls, and aws-c-common on OpenBSD 7.2/amd64. No regressions when building same packages on Ubuntu (22.04).
By adding support for OpenBSD to builder, I will be able to submit PRs to downstream CRT projects to add CI jobs for OpenBSD allowing those projects to identify regressions and breaking changes.
> Add OpenBSD as a supported build host

- .github/workflows/sanity-test.yml
Updates the version of MacOS used in the sanity test from `10.15` to `12`, so we are testing both MacOS 11 and 12 and no longer testing deprecated MacOS containers.
______
> Update MacOS version used in sanity-test

- README.md
- builder/actions/install.py
- builder/core/data.py
N/A
Tune OpenBSD support based on learnings from using crt-builder with downstream CRT projects.
- Don't explicitly install python (python has to be installed before running builder so this was redundant at best and just slowed the build at wost)
- Do install git
- Make mention of OpenBSD in the README
- Revert support for doas introduced in 88a4d05 (I've pivoted to a different GitHub action which includes sudo in its OpenBSD VM)
> Tune OpenBSD support

- .github/workflows/sanity-test.yml
- builder/actions/cmake.py
- builder/core/data.py
- builder/core/project.py
> Cross build fix

- builder/core/data.py
- builder/imports/awslc.py
> add CMake Flag for gcc 4.8 to disable AVX512-specific optimizations

- .github/workflows/create-channel.yml
- .github/workflows/sanity-test.yml
- builder/actions/cmake.py
- builder/core/data.py
- Turn on header checks by default
- Update channel if builder/** is updated
- Add MSVC 17 toolset
- Use latest github runner for Sanity test
> Turn off header checks on older MSVC compilers.

- .github/docker-images/openwrt-x64-openjdk8/Dockerfile
- Release of builder failed because https://hub.docker.com/r/openwrtorg/rootfs is returning a 404. [Openwrt](https://github.com/openwrt/docker) has switched their docker.io account from openwrtorg to openwrt. Replace the image with https://hub.docker.com/r/openwrt/rootfs. 
> Fix OpenWrt image

- builder/core/env.py
**Issue:**
Builder's "check out branches with same-name" behavior wasn't working right on Codebuild. In that environment, git reported its current branches as:
```
* (HEAD detached at 1dd6804)
stream2
remotes/origin/stream2
```
I expected it to checkout aws-c-common's `stream2` branch, but instead it tried to checkout the `(HEAD detached at 1dd6804)` branch 😐
we already had code to ignore entries like `(no branch)`, now we have code to ignore all entries starting with `(`
> Fix same-named branch behavior in Codebuild

- .github/workflows/linux-container-ci.sh
- builder/actions/cmake.py
> Use CTEST_PARALLEL_LEVEL

- .github/workflows/create-channel.yml
- .github/workflows/create-release.yml
As the raspberry image is not available right now. Always pull the latest image and push to ECR. 
> Skip Raspberry Image

- .github/workflows/sanity-test.yml
- builder/actions/setup_cross_ci_helpers.py
- builder/core/toolchain.py
- builder/imports/llvm.py
- builder/imports/nodejs.py
Python 3.12 added syntax warning (ex. SyntaxWarning: invalid escape sequence '\d') that triggers on all of our regex's. More info here. 
> Resolve regex literals warning

- builder/actions/setup_cross_ci_crt_environment.py
Used to verify new flexible custom auth signature intake (handle unencoded values properly).
> Add unencoded custom auth signature secret 

- builder/actions/setup_cross_ci_crt_environment.py
Add possibility to dump testing environment variables to a specified file. The dump file is specified via an environment variable `AWS_SETUP_CRT_TEST_ENVIRONMENT_DUMP_FILE`.
This is useful when you want to setup your local environment for running tests. Execute the following commands from the repo root to set env vars:
```sh
export AWS_SETUP_CRT_TEST_ENVIRONMENT_DUMP_FILE=~/work/setup_test_env.inc
builder run SetupCrossCICrtEnvironment -p tests
source ~/work/setup_test_env.inc
```
> Add ability to dump test env vars to file

- .github/actions/check-submodules/dist/index.js
- .github/actions/check-submodules/package-lock.json
- .github/actions/check-submodules/package.json
- .github/actions/release-tag/package-lock.json
- .github/actions/release-tag/package.json
- .github/actions/release-tag/packed/index.js
**Issue:**
Dependabot wants to bump these npm dependencies. See:
https://github.com/awslabs/aws-crt-builder/pull/252
https://github.com/awslabs/aws-crt-builder/pull/253
https://github.com/awslabs/aws-crt-builder/pull/258
https://github.com/awslabs/aws-crt-builder/pull/259
But Github actions [are weird](https://github.com/awslabs/aws-crt-builder/tree/ac26551140e6092fc3c877823b2fab8793ffaab4/.github/actions/check-submodules#notes-on-node_modules) and you need to run `npm install` and commit the artifacts after an npm update. So here's my own manual PR.
> Bump @vercel/ncc -> 0.38.1 and @actions/core -> 1.10.1

- builder/actions/setup_cross_ci_crt_environment.py
- builder/actions/setup_cross_ci_helpers.py
Temporary disable the windows certificate store setup to unblock downstream CI. 
The downstream CI test for windows could be verified at: https://github.com/awslabs/aws-crt-nodejs/pull/531
> Disable windows certificate store setup

- builder/actions/setup_cross_ci_crt_environment.py
- builder/actions/setup_cross_ci_helpers.py
Powershell 7.3 introduced an issue where launching powershell from cmd would not set PSModulePath correctly. As a workaround, we set `PSModulePath` to empty so that powershell would automatically reset the PSModulePath to default.
More details: https://github.com/PowerShell/PowerShell/issues/18530
> Fix powershell7.4 issue

- builder/core/data.py
The FreeBSD base system does not include git or cmake; builder needs to install them. Like OpenBSD, Python isn't included in base either, however the CI job installs that manually because Python is used to download builder.
> chore(ci): Install necessary packages on FreeBSD

- .github/docker-images/openwrt-x64-openjdk8/Dockerfile
- openwrt docker latest is using the SNAPSHOT version of openwrt, and it failed to install gcc
- eg: https://github.com/awslabs/aws-crt-builder/actions/runs/9373963910/job/25862946745?pr=283 
- Pin to the latest stable release resolved the build issue. https://openwrt.org/start
> Fix openwrt

- .github/docker-images/raspbian-bullseye/Dockerfile
- .github/docker-images/ubuntu-18-x64/Dockerfile
- .github/workflows/create-channel.yml
- .github/workflows/create-release.yml
**Issue:**
https://github.com/awslabs/aws-crt-python/pull/573 needs python3's `venv` installed on all docker images, due to [PEP 668](https://peps.python.org/pep-0668/).
While trying to update our `raspbian-bullseye` image, I discovered it's been broken for months. We'd been [hacking around this](https://github.com/awslabs/aws-crt-builder/pull/256) by not even trying to build it anymore, copy/pasting an old working version instead.
- Install `python3-venv` in Docker images that didn't already have it
- Fix `raspbian-bullseye` image.
- The old image was getting 404 from some repository while running `apt-get update`
- Use different base image: https://github.com/dtcooper/raspberrypi-os-docker. This was the only easily available `bullseye` image I could find. The …
> Docker images: fix raspbian-bullseye, install python3-venv

- builder/core/host.py
- builder/imports/golang.py
- builder/imports/jdk.py
- adds support for macos arm64
> Fix arm64 for MacOS

- builder/imports/awslc.py
- add compiler flag `-msse2` for aws-lc when building on x86.
- they recently added the https://github.com/aws/aws-lc/commit/6fe8dcbe96e580ea85233fdb98a142e42951b70b, which requires sse2 on x86
> add an extra compiler flag for sse2

- .github/workflows/create-channel.yml
- .github/workflows/create-release.yml
- .github/workflows/sanity-test.yml
Fixes the following dependabot PRs:
- https://github.com/awslabs/aws-crt-builder/pull/292
- https://github.com/awslabs/aws-crt-builder/pull/270
- https://github.com/awslabs/aws-crt-builder/pull/269
> Bump actions/download-artifact and actions/upload-artifact to v4

- .github/workflows/stale_issue.yml
https://github.com/awslabs/aws-crt-builder/actions/runs/10676311535
> Update stale_issue permissions to fix failing workflow

- builder/imports/awslc.py
This reverts commit 296ea50cf4169bde23a27bc725dd6fafd7a6333e.
As https://github.com/aws/aws-lc/pull/1841 merged, we should not need the workaround from downstream for the sse2 flag.
> Revert "add compiler flag `-msse2` for aws-lc on x86 (#291)"

- .github/workflows/sanity-test.yml
- builder/core/data.py
- builder/core/toolchain.py
Currently when you try to use default gcc compiler it ends up inserting version (which is 'default') into a bunch of places and the builder fails. override the packages to install to just use os defaults. 
> Fix handling of gcc compiler default case

- .github/workflows/create-release.yml
the typo in which os to use makes the job run forever trying to get the image
> Fix typo is ci jon

- .github/workflows/sanity-test.yml
Add workaround for CI. Details refer to https://github.com/awslabs/aws-crt-cpp/pull/713
> Workaround arm based CI steps

- .github/workflows/sanity-test.yml
- builder/actions/cmake.py
- builder/core/data.py
- builder/core/project.py
- builder/main.py
- tests/test_project.py
**Issue:**
Github now offers [Linux arm64 runners](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/)! But when I tried using the `ubuntu-24.04-arm` runner in aws-c-common, the unit tests didn't run.
- Remove code that assumed linux/armv8 would **always** be a cross-compile, and therefore shouldn't run tests.
- There's code in several other places ([1](https://github.com/awslabs/aws-crt-builder/blob/504fa11d0ef9e7df501dc28199ba976ffb3c631d/builder/core/project.py#L611-L628), [2](https://github.com/awslabs/aws-crt-builder/blob/504fa11d0ef9e7df501dc28199ba976ffb3c631d/builder/actions/cmake.py#L236-L243)) that stops test from running when builder is [actually …
> Support: ubuntu-24.04-arm Github runners, Amazon Linux 2023. Fix: aws-crt-cpp sanity test

- builder/actions/setup_cross_ci_crt_environment.py
XCodebuild will passing env var "TEST_RUNNER_" into tests. Setup the builder to add "TEST_RUNNER_" to environment variables when use xcodebuild. (https://developer.apple.com/documentation/xcode/environment-variable-reference)
> XCodebuild Environment Variable Setup

- builder/actions/setup_event_stream_echo_server.py
* Second branch without CI changes; intend to force merge
> Remove eventstream logging with hard-coded path

- .github/workflows/sanity-test.yml
- builder/core/data.py
The `Ubuntu-20.04` runner is not available anymore.
Some CI jobs fail on `Ubuntu-22.04`:
- clang sanity tests can't find llvm packages
- gcc sanity tests can't find gcc packages
- python3.8: not found
Update versions of the tools used in CI tests.
Checking *some* compilers in this repo's CI should be sufficient. The actual packages perform more thorough job on verifying that all supported compilers work.
> Fix CI for Ubuntu 22

- .github/docker-images/manylinux2014-x64/Dockerfile
- .github/docker-images/manylinux2014-x86/Dockerfile
- .github/workflows/create-channel.yml
- .github/workflows/sanity-test.yml
- https://github.com/pypa/manylinux/issues/1671 Manylinux dropped python3.7 
- this fix the failure of us build and publish the ECR docker image for manylinux https://github.com/awslabs/aws-crt-builder/actions/runs/17447463196/job/49545283153
- This also fixes the `swift-5-centos-x64 Sanity test`. Apparently it was removed from https://github.com/awslabs/aws-crt-builder/pull/328. But since our Sanity test only runs on specific file changes, it didn't run on that PR. That's why we missed this.
- Python3.7 is gone, use 3.8 instead
- This "SHOULD" be caught by CI `Sanity Tests / aws-c-cal (manylinux2014-x64)` and `Create Channel / manylinux2014-x86 (push)`, however, looks like we ignored the CI failures in …
> Fix bunch of CI/CD failure for builder
