awslabs/aws-crt-builder

.github/workflows/docker-images.yml, .github/workflows/lint.yml, builder/__main__.py, builder/actions/cmake.py, builder/actions/git.py, builder/config.py, builder/data.py, builder/project.py, builder/scripts.py, builder/shell.py
=> Add/Fix windows and OSX

.github/docker-images/al2-x64/Dockerfile, builder/actions/script.py, builder/config.py, builder/data.py
=> More fixes after deploying to aws-c-http

builder/actions/git.py
=> Always checkout submodules recursively

.github/docker-images/al2-arm64/Dockerfile, .github/docker-images/al2-x64/Dockerfile, .github/docker-images/alpine-armv6/Dockerfile, .github/docker-images/alpine-armv7/Dockerfile, .github/docker-images/build_cmake.sh, .github/docker-images/build_libcrypto_1.0.2.sh, .github/docker-images/build_libcrypto_1.1.1.sh, .github/docker-images/manylinux1-x64/Dockerfile, .github/docker-images/manylinux1-x86/Dockerfile, .github/docker-images/manylinux2014-x64/Dockerfile, .github/docker-images/manylinux2014-x86/Dockerfile, .github/docker-images/raspbian-armv6/Dockerfile, .github/docker-images/raspbian-armv7/Dockerfile, .github/docker-images/ubuntu-16-x64/Dockerfile, .github/workflows/docker-images.yml, .github/workflows/sanity-test.yml, builder/__main__.py, builder/actions/cmake.py, builder/actions/install.py, builder/data.py, builder/env.py, builder/project.py, builder/toolchain.py
=> Fixed libcrypto in docker containers, misc C++ fixes

.github/docker-images/entrypoint.sh, .github/docker-images/ubuntu-16-x64/Dockerfile, .github/workflows/docker-images.yml, README.md, builder/__main__.py, builder/actions/cmake.py, builder/actions/git.py, builder/actions/install.py, builder/api.py, builder/data.py, builder/env.py, builder/imports/__init__.py, builder/imports/libcrypto.py, builder/project.py, builder/scripts.py, builder/shell.py, builder/spec.py, builder/toolchain.py, builder/util.py, builder/vmod.py
Major items:
* Toolchain no longer depends on Env, so Toolchain functions can be used at any time, anywhere
* Greatly simplified arg parsing
* Added environment injection for cross-compile targets
* Fixed a bug that was causing configs to mashed into each other and becoming a mess
* Got rid of dependency on tar/curl
* Fixed a problem where GC would destroy dynamically loaded classes before we got to use them, resulting in a truly insane debugging situation
* Made sure all downloads from CloudFront use a param on the end to avoid the cache
=> Fixes found porting java/cpp/python

.github/workflows/sanity-test.yml, builder/scripts.py
=> Make sure that Action exists before looking for its subclasses

.github/workflows/docker-images.yml, .github/workflows/sanity-test.yml, builder/__main__.py, builder/imports/libcrypto.py, builder/imports/s2n.py, builder/project.py, builder/scripts.py
=> Fixed project lookup of classes when resolving source only projects

.github/workflows/sanity-test.yml, builder/actions/cmake.py, builder/actions/install.py, builder/data.py, builder/env.py, builder/project.py, builder/shell.py, builder/toolchain.py, builder/util.py
=> Fixed case where config dict was replaced and env got out of sync

.github/workflows/sanity-test.yml, builder/__main__.py, builder/actions/cmake.py, builder/actions/install.py, builder/data.py, builder/imports/dockcross.py, builder/imports/gcc.py, builder/imports/libcrypto.py, builder/imports/llvm.py, builder/imports/msvc.py, builder/imports/s2n.py, builder/project.py, builder/toolchain.py, builder/util.py
Also fixed bug where configs where multiple branches of a config would get doubled up
=> Compilers are now imports, install clang via modified llvm.sh

.github/docker-images/al2012-x64/Dockerfile, .github/docker-images/build_cmake.sh, .github/docker-images/build_libcrypto_1.0.2.sh, .github/docker-images/build_libcrypto_1.1.1.sh, .github/docker-images/build_node_10.x.sh, .github/docker-images/cache_maven.sh, .github/workflows/docker-images.yml
=> Added al2012 docker image and build job

builder/imports/llvm.py
=> Use LLVM_VERSION_STRING as suffix

.github/docker-images/entrypoint.sh, .github/workflows/docker-images.yml, builder/fetch.py, builder/project.py
=> Builder should find any project in a dir with builder.json in it

.github/workflows/docker-images.yml
=> Fixed dependencies for linux aws-c-common test build

.github/docker-images/entrypoint.sh, .github/workflows/docker-images.yml
=> Fix entrypoint

.github/docker-images/entrypoint.sh, .github/workflows/docker-images.yml
=> Update ECR for each release

.github/docker-images/build_libcrypto_1.0.2.sh, .github/docker-images/build_libcrypto_1.1.1.sh, .github/workflows/docker-images.yml, .github/workflows/sanity-test.yml, builder/actions/cmake.py, builder/data.py, builder/env.py, builder/imports/jdk.py, builder/imports/libcrypto.py, builder/imports/s2n.py, builder/project.py, builder/util.py
* Fixed case where deps could be installed multiple times because multiple copies of the import were instantiated
* Fixed project directory overrides
=> More fixes

builder/imports/libcrypto.py
=> libcrypto 1.0.2 for manylinux

.github/workflows/sanity-test.yml, builder/fetch.py, builder/imports/jdk.py, builder/imports/libcrypto.py, builder/imports/nodejs.py
NOTE: This won't actually improve anything until the publish step is added to dependencies which uploads the repo manifest, but I want to get the API in place before writing more download code for Android and other dependencies.
=> Implemented Fetch API, added deps cache

.github/docker-images/crossbuild_libcrypto_1.1.1.sh, .github/docker-images/entrypoint.sh, .github/workflows/docker-images.yml, builder/__main__.py, builder/actions/mirror.py, builder/data.py, builder/env.py, builder/fetch.py, builder/imports/ndk.py, builder/project.py, builder/util.py
=> Added android as a target platform

.github/docker-images/entrypoint.sh
=> Fixed bad merge

.github/workflows/create-release.yml
=> Release releases to... releases, not channels

.github/docker-images/al2-x64/Dockerfile, .github/docker-images/al2012-x64/Dockerfile, .github/docker-images/crossbuild_libcrypto_1.1.1.sh, .github/docker-images/node-10-linux-x64/Dockerfile, .github/workflows/docker-images.yml
*Issue #, if available:* https://github.com/aws/aws-iot-device-sdk-js-v2/issues/26
=> Added node docker image

builder/fetch.py, builder/project.py, builder/scripts.py
Issues found while working on https://github.com/awslabs/aws-crt-dotnet/pull/19
=> Fixed script imports of nested subclasses

.github/workflows/create-channel.yml, .github/workflows/create-release.yml
=> added node image to channel/release creation workflows

.github/docker-images/entrypoint.sh, builder/host.py
=> Host detection

.github/docker-images/node-10-linux-x64/Dockerfile
=> Swapped node10 image to be centos7 based for glibc 2.17

.github/docker-images/entrypoint.sh
=> Added support for finding working directory via codebuild

.github/docker-images/build_cmake.sh, .github/docker-images/node-10-linux-x64/Dockerfile, .github/workflows/create-release.yml
=> Fixed cmake build script, added prebuilt cmake to node image

.github/workflows/sanity-test.yml, builder/actions/release.py
=> fix warning msg in release-notes cmd

.github/docker-images/al2-x64/Dockerfile, .github/docker-images/al2012-x64/Dockerfile, .github/docker-images/manylinux2014-x64/Dockerfile, .github/docker-images/ubuntu-16-x64/Dockerfile
=> Pull Customized CMake From S3

builder/data.py
=> Install libstdc++ for clang

.github/workflows/sanity-test.yml, builder/imports/gcc.py, builder/imports/llvm.py, builder/imports/msvc.py
=> LLVM now installs compiler_packages

builder/data.py
=> Ensure clang/gcc install libstdc++ that corresponds to their version

builder/data.py
=> fix clang6

README.md
=> Added additional helpful docs to builder README

.github/docker-images/swift-5-al2-x64/Dockerfile, .github/docker-images/swift-5-centos-x64/Dockerfile, .github/docker-images/swift-5-ubuntu-16-x64/Dockerfile, .github/workflows/create-channel.yml, .github/workflows/create-release.yml, .github/workflows/docker-images.yml, .github/workflows/sanity-test.yml
*Description of changes:* Adding swift docker images to add swift support for swift crt bindings CI
=> Swift Support

builder/data.py
=> Added iOS as a target

.github/docker-images/manylinux1-x64/Dockerfile, .github/docker-images/manylinux1-x86/Dockerfile, .github/docker-images/manylinux2014-x64/Dockerfile, .github/docker-images/manylinux2014-x86/Dockerfile
=> Added libcrypto pre-install to manylinux images

.github/docker-images/crossbuild_libcrypto_1.1.1.sh, .github/docker-images/entrypoint.sh, .github/docker-images/manylinux2014-aarch64/Dockerfile, .github/workflows/create-channel.yml, .github/workflows/create-release.yml, .github/workflows/docker-images.yml, .github/workflows/sanity-test.yml, builder/actions/install.py, builder/data.py, builder/host.py, builder/imports/libcrypto.py, builder/spec.py, builder/toolchain.py
=> Added manylinux2014-aarch64 docker image

builder/data.py
=> Added osx as an alias for macos/darwin

.github/workflows/create-channel.yml, .github/workflows/create-release.yml, builder/project.py
=> Always run downstream tests by default

builder/env.py, builder/project.py
=> cli config can apply non-boolean values now

builder/data.py, builder/toolchain.py
=> Fixed ios armv8 aliases, fixed cross compile logic for ios

.github/workflows/create-release.yml
=> Fix the lack of set-env in release pipeline

.github/workflows/create-channel.yml, .github/workflows/create-release.yml
=> Standardized release tag parsing

.github/workflows/create-channel.yml, .github/workflows/create-release.yml
=> Removed dependency on tag job which was removed

.github/workflows/create-release.yml
=> Allow releases to be re-run manually

.github/workflows/create-channel.yml, .github/workflows/create-release.yml
=> Fixed step output references

builder/imports/nodejs.py
=> Addressing Windows NodeJS not being found on path issue

.github/docker-images/php5-linux-x64/Dockerfile, .github/docker-images/php7-linux-x64/Dockerfile, .github/workflows/create-channel.yml, .github/workflows/create-release.yml, .github/workflows/docker-images.yml
=> Added PHP 5.6 and PHP 7.4 docker images

builder/imports/s2n.py
=> Switched s2n from depending on libcrypto to aws-lc

builder/actions/cmake.py, builder/core/project.py, builder/imports/awslc.py, builder/imports/s2n.py
=> aws-lc/s2n fixes

builder/actions/cmake.py
also delete folder that was checked in by accident
=> check for cmake3 alias

builder/core/project.py
upstream tests were building if they had "test_steps" defined
upstream tests should never build
=> don't build upstream tests

builder/imports/llvm.py
=> Add new clang versions as possible compiler targets

.github/docker-images/debian-stretch-arm32v5/Dockerfile, .github/docker-images/debian-stretch-arm32v7/Dockerfile, builder/core/data.py
* Separated Debian from Ubuntu in OS configuration
=> Added python to docker image and AWS CLI

builder/imports/llvm.py
=> updated llvm script to support ubuntu 20 variants

.github/docker-images/swift-5-al2-x64/Dockerfile, .github/docker-images/swift-5-centos-x64/Dockerfile, .github/docker-images/swift-5-ubuntu-16-x64/Dockerfile, builder/actions/install.py, builder/core/data.py, builder/core/host.py, builder/core/shell.py
=> Fixes for swift

.github/workflows/create-channel.yml, .github/workflows/create-release.yml, .github/workflows/docker-images.yml
=> fixed up publishing steps, docker -> s3, php image publishing

.github/docker-images/phpbrew-linux-x64/Dockerfile, .github/workflows/create-channel.yml, .github/workflows/create-release.yml, .github/workflows/docker-images.yml
=> Removed redundant php installs and added phpbrew use to /etc/environment

.github/docker-images/entrypoint.sh, .github/docker-images/phpbrew-linux-x64/Dockerfile
=> Fix php version selection in docker images

.github/workflows/create-release.yml, .github/workflows/docker-images.yml
=> Fix release build for php docker images

.github/workflows/sanity-test.yml, builder/actions/cmake.py, builder/core/project.py
=> Always pushd/popd project directory when executing project steps

.github/workflows/sanity-test.yml, builder/actions/cmake.py, builder/actions/install.py, builder/core/project.py, builder/core/toolchain.py, builder/core/util.py, builder/imports/awslc.py
=> Testing clean up/fixes

.github/docker-images/manylinux2014-aarch64/Dockerfile
=> Install node on the manylinux aarch64 image

builder/actions/install.py
=> Use correct variable

.github/docker-images/ubuntu-20-aarch64/Dockerfile, .github/workflows/create-channel.yml, .github/workflows/create-release.yml, .github/workflows/docker-images.yml
=> Ubuntu 20 arm64 image

.github/workflows/create-channel.yml, .github/workflows/create-release.yml, .github/workflows/docker-images.yml, .github/workflows/sanity-test.yml
=> First draft - use ecr exclusively

.github/workflows/create-release.yml
* Names were wrong and php release actions failed as a result
=> Fix names on php image release

.github/docker-images/fedora-34-x64/Dockerfile, .github/docker-images/opensuse-leap/Dockerfile, .github/docker-images/rhel8-x64/Dockerfile, builder/core/data.py, builder/core/host.py, builder/imports/s2n.py
* Host definitions for new linux flavors
* Disable warnings on s2n builds
* Update new linux flavor containers a little
=> Linux flavor hosts

.github/workflows/create-release.yml
=> Wrong image name when creating latest tag for php images

builder/imports/s2n.py
=> s2n's config wasn't getting passed into the Project constructor correctly

.github/workflows/create-release.yml, .github/workflows/linux-container-ci.sh
=> Upload simple ci-via-container script as part of release process

.github/workflows/linux-container-ci.sh
=> Pass CXXFLAGS to builder environment to support C++ stdlib variation CI

.github/workflows/create-channel.yml, .github/workflows/docker-images.yml, builder/imports/nodejs.py
=> Added node 12-18 support, fixed ECR integration

builder/core/data.py
=> Added support for Apple watchOS and tvOS

.github/docker-images/swift-5-al2-x64/Dockerfile, .github/docker-images/swift-5-centos-x64/Dockerfile, .github/docker-images/swift-5-ubuntu-x64/Dockerfile
*Description of changes:* Update images to use swift 5.5
=> fix: update images to use swift 5.5

.github/workflows/create-channel.yml, .github/workflows/create-release.yml
=> Fix release/channel ECR repo usage

.github/docker-images/fedora-34-x64/Dockerfile, .github/docker-images/opensuse-leap/Dockerfile, .github/docker-images/rhel8-x64/Dockerfile
* Add awscli to base images
* Add softhsm to opensuse image, punting on adding to other linux flavors
=> Image updates

.github/docker-images/fedora-34-x64/Dockerfile, .github/docker-images/opensuse-leap/Dockerfile, .github/docker-images/rhel8-x64/Dockerfile
=> Add python3-devel install to all linux flavor containers

.github/docker-images/fedora-34-x64/Dockerfile, .github/docker-images/opensuse-leap/Dockerfile
=> Add some utilities needed by the node install script

.github/docker-images/swift-5-al2-x64/Dockerfile, .github/docker-images/swift-5-centos-x64/Dockerfile, .github/docker-images/swift-5-ubuntu-x64/Dockerfile
*Description of changes:* This update to use the latest version of swift corrects some bugs on Linux in regards to the new swift concurrency primitives and support.
=> fix: update docker images to use latest version of swift for async support

builder/actions/cmake.py
**Issue:**
I wasn't able to tweak the cmake args for aws-crt-cpp the way I wanted via builder.json's data merging powers.
Offer programmatic way to tweak the cmake args
=> allow cmake_args to be tweaked via code

.github/workflows/create-channel.yml, .github/workflows/create-release.yml, .github/workflows/sanity-test.yml
https://github.com/awslabs/aws-crt-builder/issues/159
=> Update to v2 of actions/checkout

builder/core/env.py
=> no branch expection

.github/docker-images/opensuse-leap/Dockerfile
=> Remove HSM install from opensuse container def

.github/docker-images/manylinux1-x64/Dockerfile, .github/docker-images/manylinux1-x86/Dockerfile, .github/workflows/create-channel.yml, .github/workflows/create-release.yml, .github/workflows/sanity-test.yml
=> Attempt to restore manylinux1 image build and publish

builder/actions/script.py
- Fixes an issue where install_dir was not interpolated in a downstream build.
=> Fix Interpolation

builder/imports/nodejs.py
Pull Node build from https://unofficial-builds.nodejs.org/ for x86 platforms
=> Pull Node x86 build for x86 platform

.github/actions/check-submodules/dist/index.js, .github/actions/check-submodules/package-lock.json, .github/actions/check-submodules/package.json, .github/actions/release-tag/index.js, .github/actions/release-tag/package-lock.json, .github/actions/release-tag/package.json, .github/actions/release-tag/packed/index.js, .github/workflows/create-channel.yml, .github/workflows/create-release.yml, .github/workflows/lint.yml, .github/workflows/sanity-test.yml, builder/imports/llvm.py
=> update NPM dependencies

builder/actions/cmake.py, builder/core/data.py, builder/core/toolchain.py, builder/main.py
Change default sanitizer configurations. Minor other changes
=> San update

.gitignore, README.md, builder/core/data.py, builder/core/spec.py, builder/core/toolchain.py, builder/main.py
Untangle apple clang from regular clang
=> Appleclang (WIP)

.github/docker-images/al2-x64/Dockerfile, .github/docker-images/al2012-x64/Dockerfile, .github/docker-images/debian-stretch-arm32v5/Dockerfile, .github/docker-images/debian-stretch-arm32v7/Dockerfile, .github/docker-images/fedora-34-x64/Dockerfile, .github/docker-images/manylinux1-x64/Dockerfile, .github/docker-images/manylinux1-x86/Dockerfile, .github/docker-images/manylinux2014-aarch64/Dockerfile, .github/docker-images/manylinux2014-armv7l/Dockerfile, .github/docker-images/manylinux2014-x64/Dockerfile, .github/docker-images/manylinux2014-x86/Dockerfile, .github/docker-images/node-10-linux-x64/Dockerfile, .github/docker-images/opensuse-leap/Dockerfile, .github/docker-images/raspbian-bullseye/Dockerfile, .github/docker-images/rhel8-x64/Dockerfile, .github/docker-images/swift-5-al2-x64/Dockerfile, .github/docker-images/swift-5-centos-x64/Dockerfile, .github/docker-images/ubuntu-18-x64/Dockerfile, .github/docker-images/ubuntu-20-aarch64/Dockerfile, .github/docker-images/ubuntu-20-x64/Dockerfile
=> Fix AL2 docker image build

.github/actions/check-submodules/action.yml, .github/actions/check-submodules/package-lock.json, .github/actions/check-submodules/package.json, .github/actions/release-tag/action.yml, .github/actions/release-tag/package-lock.json, .github/actions/release-tag/package.json, .github/docker-images/openwrt-x64-openjdk8/Dockerfile
bump node version and update deps
=> Bump node version for actions

builder/actions/cmake.py, builder/actions/git.py, builder/core/project.py, builder/imports/boringssl.py
Support building aws-c-cal against boringssl
=> BorringSSL support

builder/core/data.py
=> clang supports freebsd

.github/docker-images/ubuntu-22-x64/Dockerfile, .github/workflows/create-channel.yml
=> Ubuntu 22.04 image

.github/docker-images/manylinux2014-aarch64/Dockerfile
=> Move Aarch64  CD image to node 14

.github/docker-images/swift-5-al2-x64/Dockerfile, .github/docker-images/swift-5-centos-x64/Dockerfile, .github/docker-images/swift-5-ubuntu-x64/Dockerfile
=> Update Swift from 5.5 to 5.7

.github/actions/check-submodules/index.js, builder/core/data.py
=> support fips branch for aws-lc

.github/actions/check-submodules/dist/index.js, .github/actions/check-submodules/package-lock.json, .github/actions/release-tag/package-lock.json, .github/actions/release-tag/packed/index.js
=> Bump undici from 5.28.2 to 5.28.4

builder/imports/awslc.py
=> Disable perl for old GCC

.github/workflows/sanity-test.yml
=> macos-11 is gone

.github/workflows/linux-container-ci.sh, builder/actions/setup_cross_ci_crt_environment.py
=> Fix Environment for Temporary Creds

.github/workflows/create-channel.yml
Issue similar to https://github.com/nodejs/docker-node/issues/2124
specify explicit platform to pull for the image
=> Fix ubuntu aarch64 metadata not being found when building images

.github/workflows/create-release.yml
=> add create channel ubuntu fix to create release

.github/actions/check-submodules/dist/index.js, .github/actions/check-submodules/index.js, .github/actions/check-submodules/package-lock.json, .github/actions/release-tag/package-lock.json, .github/actions/release-tag/packed/index.js
=> Update FIPS branch
